// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPvmemesCIDFmd0LfcVnnNjhpw--z2e9w',
    appId: '1:1024665293952:web:635d3fb216e5a15ce78265',
    messagingSenderId: '1024665293952',
    projectId: 'with-diet',
    authDomain: 'with-diet.firebaseapp.com',
    storageBucket: 'with-diet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIsVNtCSKWb2ZoCAzSy2tCWOQdITBgQRM',
    appId: '1:1024665293952:android:f1c297afa18ffb74e78265',
    messagingSenderId: '1024665293952',
    projectId: 'with-diet',
    storageBucket: 'with-diet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6xCzfCUHshQkLpl8c4hIDi-zh7j0nmsM',
    appId: '1:1024665293952:ios:f8f0e1071a3bb589e78265',
    messagingSenderId: '1024665293952',
    projectId: 'with-diet',
    storageBucket: 'with-diet.firebasestorage.app',
    iosBundleId: 'com.wonjongseo.with-diet',
  );
}
